### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by avestura** [FuncUI/Avalonia.FuncUI.ProjectTemplates#5]
I get `System.MissingMethodException` when I want to open Profiles tab of quickstart template.

```
System.MissingMethodException: Method not found: 'Microsoft.FSharp.Control.FSharpAsync`1<System.IO.TextReader> FSharp.Data.Runtime.IO.asyncReadTextAtRuntime(System.Boolean, System.String, System.String, System.String, System.String, System.String)'.
   at SG.CodeCoverage.Inspector.Core.Users.getUsers@19.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
```

**Comment by AngelMunoz** [comment]
Hi! thanks for the issue
I have a couple of questions
would you tell me which version of .net core are you using?
does the error disappears if you add a reference to the latest FSharp.Core package?

**Comment by avestura** [comment]
The latest version of .NET Sdk that I have is `5.0.100-preview.1.20155.7 [C:\Program Files\dotnet\sdk]` and while building it says `"You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview"`.
Adding reference to `FSharp.Core` version `4.7.1` didn't help.

**Comment by avestura** [comment]
However this is the result of my list-sdks
```
❯ dotnet --list-sdks
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]
3.0.100 [C:\Program Files\dotnet\sdk]
3.1.100 [C:\Program Files\dotnet\sdk]
3.1.201 [C:\Program Files\dotnet\sdk]
5.0.100-preview.1.20155.7 [C:\Program Files\dotnet\sdk]
```

**Comment by avestura** [comment]
https://github.com/fsharp/FSharp.Data/issues/605

Someone else also has this problem with .NET 5

**Comment by AngelMunoz** [comment]
Ah you are right 
https://github.com/dotnet/fsharp/issues/8743

it seems it has been fixed in https://github.com/dotnet/fsharp/pull/8963
I expect once the next preview for F# is out it will get fixed

**Comment by AngelMunoz** [comment]
you can in the meantime use a global.json
```json
{
  "sdk": {
    "version": "3.1.201"
  }
}
```
as mentioned on one of those issues

**Comment by avestura** [comment]
Yeah right, it fixes it. Thank you.
