### ISSUE TITLE
DockPanel.create deprecated?

### ISSUE THREAD

**Issue by mpblackman** [FuncUI/Avalonia.FuncUI.ProjectTemplates#6]
Just trying out the counter.fs template, getting issues with DockPanel.create.
Am trying something like this but it generates an issue in the main prog (my F# skills are rudimentary).
```Fsharp
   let view (state: State) (dispatch) =
        let myDockPanel = new DockPanel()
        let button1 = new Button()
        let button2 = new Button()
        let button3 = new Button()
        button1.Content <- "reset"
        button2.Content <- "-"
        button3.Content <- "+"
        button1.Command <- dispatch Reset
        button2.Command <- dispatch Decrement
        button3.Command <- dispatch Increment
        myDockPanel.Children.Add(button1)
        myDockPanel.Children.Add(button2)
        myDockPanel.Children.Add(button3)
```

**Comment by AngelMunoz** [comment]
Hi there, 
Every control has a DSL you can use to create your UI's every control has a module that contains the functions you need to create it
in your case, the view function should look something like this

```fsharp
let view (state : State ) (dispatch : Msg -> unit) =
    DockPanel.create [
        DockPanel.children [
            Button.create [ Button.content "-"; Button.onClick(fun _ -> dispatch Decrement) ]
            Button.create [ Button.content "+"; Button.onClick(fun _ -> dispatch Increment) ]
            Button.create [ Button.content "Reset"; Button.onClick(fun _ -> dispatch Reset) ]
            TextBlock.create [ TextBlock.text (state.count |> str)]
        ]
    ]
```
also you can specify the position within the dock panel like this 
```fsharp
Button.create [ Button.dock Dock.Top; Button.content "-"; Button.onClick(fun _ -> dispatch Decrement) ]
```
you can also check the docs (there are a lot of controls missing  it's on the works) for the button control 
https://avaloniacommunity.github.io/Avalonia.FuncUI.Docs/controls/Button.html

**Comment by AngelMunoz** [comment]
also you need these namespaces open at the top of your file
```fsharp
open Avalonia.FuncUI
open Avalonia.FuncUI.DSL // specially this one
```

**Comment by mpblackman** [comment]
Thank you very much for the help. I had added Avalonia.FuncUI in reference manager but hadn't noticed that Avalonia.FuncUI.DSL was a separate package; DockPanel was thus being seen as Avalonia.Controls.DockPanel.

**Comment by AngelMunoz** [comment]
Ah in that case be sure to include three packages
```xml
<PackageReference Include="JaggerJo.Avalonia.FuncUI" Version="0.4.1" />
<PackageReference Include="JaggerJo.Avalonia.FuncUI.DSL" Version="0.4.3" />
<PackageReference Include="JaggerJo.Avalonia.FuncUI.Elmish" Version="0.4.0" />
```

there's also the dotnet templates as well

```sh
dotnet new --install JaggerJo.Avalonia.FuncUI.Templates
```
after running that you can just type
```
dotnet new funcui.basic -n NewApp
```
and it will generate you a working basic sample


you can check with a little bit more in detail here
https://avaloniacommunity.github.io/Avalonia.FuncUI.Docs/guides/Home.html
https://avaloniacommunity.github.io/Avalonia.FuncUI.Docs/guides/Basic-Template.html

you can also reach in the gitter  channel
https://gitter.im/Avalonia-FuncUI/community
